proj/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pricecheck.urls')),
]

proj/fund/urls.py
from django.urls import path
from . import views

app_name = "fund"

urlpatterns = [
    path("", views.index, name="index"),
    path("schedule/", views.schedule, name="schedule"),
    path("schedule/change_status", views.change_status, name="schedule_change_status"),
    path("fund/", views.fund, name="fund"),
    path(
        "fund/<str:sec_type>/<str:fund_id>/<str:date_close>",
        views.fund_transfer,
        name="fund_transfer",
    ),
    path("fund/dashboard/divlist/", views.dashboard_divlist, name="dashboard_divlist"),
]

proj/pricecheck/urls.py
from django.urls import path
from . import views

app_name = "pricecheck"

urlpatterns = [
    path("", views.index, name="index"),
    path("schedule/", views.schedule, name="schedule"),
    path("schedule/change_status", views.change_status, name="schedule_change_status"),
    path("fund/", views.fund, name="fund"),
    path(
        "pricecheck/<str:sec_type>/<str:fund_id>/<str:date_close>",
        views.pricecheck_transfer,
        name="pricecheck_transfer",
    ),
    path("pricecheck/dashboard/divlist/", views.dashboard_divlist, name="dashboard_divlist"),
]

proj/pricecheck/models.py
from django.db import models


proj/pricecheck/forms.py
from django import forms


class QueryForm(forms.Form):
    fund_id = forms.CharField(label="Fund ID", max_length=4, required=True)
    as_of_date = forms.DateField(
        label="As of Date", required=True, input_formats=["%Y-%m-%d"]
    )

proj/fund/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

import datetime
from .forms import QueryForm


def index(request):
    return redirect("fund:schedule")


def schedule(request):
    if request.method == "POST":
        pass

    schedules = list()
    schedules = [
        {
            "fund_id": "9998",
            "fund_name": "ファンド9998",
            "date_close": datetime.datetime(2023, 1, 23),
            "sec_type": 0,
            "chosho_statu": "出力済み",
        },
        {
            "fund_id": "9998",
            "fund_name": "ファンド9998",
            "date_close": datetime.datetime(2023, 1, 23),
            "sec_type": 1,
            "chosho_statu": "出力済み",
        },
        {
            "fund_id": "9998",
            "fund_name": "ファンド9998",
            "date_close": datetime.datetime(2023, 1, 23),
            "sec_type": 2,
            "chosho_statu": "出力済み",
        },
        {
            "fund_id": "9997",
            "fund_name": "ファンド9997",
            "date_close": datetime.datetime(2023, 2, 23),
            "sec_type": 0,
            "chosho_statu": "データ待ち",
        },
        {
            "fund_id": "9997",
            "fund_name": "ファンド9997",
            "date_close": datetime.datetime(2023, 2, 23),
            "sec_type": 1,
            "chosho_statu": "データ待ち",
        },
        {
            "fund_id": "9997",
            "fund_name": "ファンド9997",
            "date_close": datetime.datetime(2023, 2, 23),
            "sec_type": 2,
            "chosho_statu": "データ待ち",
        },
        {
            "fund_id": "9996",
            "fund_name": "ファンド9996",
            "date_close": datetime.datetime(2023, 3, 23),
            "sec_type": 0,
            "chosho_statu": "計算中",
        },
        {
            "fund_id": "9996",
            "fund_name": "ファンド9996",
            "date_close": datetime.datetime(2023, 3, 23),
            "sec_type": 6,
            "chosho_statu": "計算中",
        },
    ]
    context = dict()
    context["schedules"] = schedules

    return render(request, "fund/schedule.html", context)


def change_status(request):
    pass


def fund(request):
    if request.method == "POST":
        form = QueryForm(request.POST)
        if form.is_valid():
            fund_id = form.cleaned_data["fund_id"]
            as_of_date = form.cleaned_data["as_of_date"]
        context = {"form": form}
        return render(request, "fund/fund.html", context)
    else:
        form = QueryForm()
        context = {"form": form}
        return render(request, "fund/fund.html", context)


def fund_transfer(request, sec_type, fund_id, date_close):
    as_of_date = datetime.datetime.strptime(date_close, "%Y-%m-%d").date()
    initial_dict = dict(fund_id=fund_id, as_of_date=as_of_date)
    form = QueryForm(initial=initial_dict)

    context = {"form": form}

    return render(request, "fund/fund.html", context)


def dashboard_divlist(request):
    d_div = [{"fund_id": 9998}, {"fund_id": 9998}]

    context = {"d_div": d_div}

    return render(request, "fund/dashboard_divlist.html", context)

proj/pricecheck/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

import datetime
from .forms import QueryForm


def index(request):
    return redirect("pricecheck:schedule")


def schedule(request):
    if request.method == "POST":
        pass

    schedules = list()
    schedules = [
        {
            "fund_id": "9998",
            "fund_name": "ファンド9998",
            "date_close": datetime.datetime(2023, 1, 23),
            "sec_type": 0,
            "chosho_statu": "出力済み",
        },
        {
            "fund_id": "9998",
            "fund_name": "ファンド9998",
            "date_close": datetime.datetime(2023, 1, 23),
            "sec_type": 1,
            "chosho_statu": "出力済み",
        },
        {
            "fund_id": "9998",
            "fund_name": "ファンド9998",
            "date_close": datetime.datetime(2023, 1, 23),
            "sec_type": 2,
            "chosho_statu": "出力済み",
        },
        {
            "fund_id": "9997",
            "fund_name": "ファンド9997",
            "date_close": datetime.datetime(2023, 2, 23),
            "sec_type": 0,
            "chosho_statu": "データ待ち",
        },
        {
            "fund_id": "9997",
            "fund_name": "ファンド9997",
            "date_close": datetime.datetime(2023, 2, 23),
            "sec_type": 1,
            "chosho_statu": "データ待ち",
        },
        {
            "fund_id": "9997",
            "fund_name": "ファンド9997",
            "date_close": datetime.datetime(2023, 2, 23),
            "sec_type": 2,
            "chosho_statu": "データ待ち",
        },
        {
            "fund_id": "9996",
            "fund_name": "ファンド9996",
            "date_close": datetime.datetime(2023, 3, 23),
            "sec_type": 0,
            "chosho_statu": "計算中",
        },
        {
            "fund_id": "9996",
            "fund_name": "ファンド9996",
            "date_close": datetime.datetime(2023, 3, 23),
            "sec_type": 6,
            "chosho_statu": "計算中",
        },
    ]
    context = dict()
    context["schedules"] = schedules

    return render(request, "pricecheck/schedule.html", context)


def change_status(request):
    pass


def fund(request):
    if request.method == "POST":
        form = QueryForm(request.POST)
        if form.is_valid():
            fund_id = form.cleaned_data["fund_id"]
            as_of_date = form.cleaned_data["as_of_date"]
        context = {"form": form}
        return render(request, "pricecheck/fund.html", context)
    else:
        form = QueryForm()
        context = {"form": form}
        return render(request, "pricecheck/fund.html", context)


def pricecheck_transfer(request, sec_type, fund_id, date_close):
    as_of_date = datetime.datetime.strptime(date_close, "%Y-%m-%d").date()
    initial_dict = dict(fund_id=fund_id, as_of_date=as_of_date)
    form = QueryForm(initial=initial_dict)

    context = {"form": form}

    return render(request, "pricecheck/pricecheck.html", context)


def dashboard_divlist(request):
    d_div = [{"fund_id": 9998}, {"fund_id": 9998}]

    context = {"d_div": d_div}

    return render(request, "pricecheck/dashboard_divlist.html", context)

proj/templates/fund/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="{% static 'fund/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fund/bootstrap-table/css/bootstrap-table.min.css' %}">
  <script src="{% static 'fund/jQuery/jquery-3.6.4.min.js' %}"></script>
  <script src="{% static 'fund/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'fund/bootstrap-table/js/bootstrap-table.min.js' %}"></script>
  <title>sample app</title>
</head>

<body class="d-flex flex-column min-vh-100 vh-100">
  <div class="container-fluid">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'fund:schedule' %}">時価チェックapp</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <ui class="nav-item">
                <a class="nav-link {%block schedule%}{%endblock%}" href="{% url 'fund:schedule' %}">Schedule</a>
              </ui>
              <ui class="nav-item">
                <a class="nav-link {%block fund%}{%endblock%}" href="{% url 'fund:fund' %}">Fund</a>
              </ui>
              <ui class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'fund:dashboard_divlist' %}" role="button"
                  data-bs-toggle="dropdown">Dashboard</a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item {% block dashboard_divlist %}{% endblock %}"
                      href="{% url 'fund:dashboard_divlist' %}">1.list_1</a>
                  </li>
                </ul>
              </ui>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  </div>

  {% block Content %}
  {% endblock Content %}

</body>

<footer class="sticky-footer bg-primary text-white my-4">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright</span>
    </div>
  </div>
</footer>

</html>

proj/templates/fund/dashboard_divlist.html
{% extends 'fund/base.html' %}
{% block dashboard %}active{% endblock %}
{% block dashboard_divlist %}active{% endblock %}

{% block Content %}
<div class="container-fluid">
    <div class="row">
        {% include 'fund/partials/dashboard_sidebar.html' with dashboard_divlist="active" %}
        <div class="col-md-10">
            <div class="container-fluid">
                <br>
                <div class="card-header">
                    <div class="d-flex">
                        <h6 class="m-0-fonnr-weight-bold text-primary">時価乖離リスト</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover table-sm" style="table-layout;fixed"
                                data-toggle="table" data-search="true">
                                <thead>
                                    <tr>
                                        <th data-width="50px" data-halign="center" data-align="right">#</th>
                                        <th data-width="100px" data-halign="center" data-align="right">ファンドコード</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in d_div %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{i.fund_id|default_if_none:''}}</td>

                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

proj/templates/fund/fund.html
{% extends 'fund/base.html' %}
{% block fund %}active{% endblock %}

{% block Content %}
<div class="container-fluid">
    <div id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse min-vh-100">
        <div class="position-sticky pt-3">
            <form method="POST">
                {%csrf_token%}
                <div>
                    <label>{{form.fund_id.label}}:</label>
                    <br>
                    {{form.fund_id}}
                </div>
                <div>
                    <label>{{form.as_of_date.label}}:</label>
                    <br>
                    {{form.as_of_date}}
                </div>
                <hr>
                <button type="submit" class="btn btn-primary btn-sw w-100">load</button>
            </form>
        </div>
    </div>
    <main class="col-md-9 ms-sm-auto col-lg-10 pt-md-4">

    </main>
</div>
{% endblock %}

proj/templates/fund/partials/dashboard_sidebar.html
<div class="col-md-2 bg-light min-vh-100">
    <br>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{% url 'fund:dashboard_divlist' %}" class="nav-link {{dashboard_divlist}}">
                時価乖離リスト
            </a>
        </li>
    </ul>
</div>

proj/templates/fund/partials/modal.html
<div class="modal fade" id="exampleModalToggle" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalToggleLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h6>入力データ状況</h6>
                <table border="1" style="width:100%">
                    <tr>
                        <td>○</td>
                        <td>作業日</td>
                        <td>2023-04-11</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>残高日</td>
                        <td>2023-04-11</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>時価取得日</td>
                        <td>2023-04-11</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>決算日</td>
                        <td>2023-04-11</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>ファンドタイプ</td>
                        <td>通常ファンド</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>中間／期末</td>
                        <td>中間</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>為替レート</td>
                        <td>取得済み</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>時価</td>
                        <td>取得済み</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A.ダウンロード</td>
                        <td>C:\Tmp\残高.xls</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A.ダウンロード(PY)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A2.ダウンロード(円建外債)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A2.ダウンロード(円建外債)(PY)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A3.ダウンロード(CP)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A3.ダウンロード(CP)(PY)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A4.外国WPM</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A5.国内取引経過</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A6.外国取引経過(円建外債)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A7.CP取引経過</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>B.有価証券明細</td>
                        <td>元データファイル不明</td>
                    </tr>

                </table>
            </div>
            <div class="modal-footer">
                <div class="container">
                    <div class="row gy-2">
                        <div class="col-6">
                            <button type="button" class="btn btn-primary w-100">銘柄別明細</button>
                        </div>
                        <div class="col-6">
                            <button type="button" class="btn btn-primary w-100">FSチェック用</button>
                        </div>
                        <div class="col-6">
                            <button type="button" class="btn btn-primary w-100">休日外国アキュム単価反映</button>
                        </div>
                        <div class="col-6">
                            <button type="button" class="btn btn-primary w-100">評価差額追加検証</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

proj/templates/pricecheck/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="{% static 'pricecheck/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'pricecheck/bootstrap-table/css/bootstrap-table.min.css' %}">
  <script src="{% static 'pricecheck/jQuery/jquery-3.6.4.min.js' %}"></script>
  <script src="{% static 'pricecheck/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'pricecheck/bootstrap-table/js/bootstrap-table.min.js' %}"></script>
  <title>sample app</title>
</head>

<body class="d-flex flex-column min-vh-100 vh-100">
  <div class="container-fluid">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'pricecheck:schedule' %}">時価チェックapp</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <ui class="nav-item">
                <a class="nav-link {%block schedule%}{%endblock%}" href="{% url 'pricecheck:schedule' %}">Schedule</a>
              </ui>
              <ui class="nav-item">
                <a class="nav-link {%block fund%}{%endblock%}" href="{% url 'pricecheck:fund' %}">Fund</a>
              </ui>
              <ui class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'pricecheck:dashboard_divlist' %}" role="button"
                  data-bs-toggle="dropdown">Dashboard</a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item {% block dashboard_divlist %}{% endblock %}"
                      href="{% url 'pricecheck:dashboard_divlist' %}">1.list_1</a>
                  </li>
                </ul>
              </ui>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  </div>

  {% block Content %}
  {% endblock Content %}

</body>

<footer class="sticky-footer bg-primary text-white my-4">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright</span>
    </div>
  </div>
</footer>

</html>

proj/templates/pricecheck/dashboard_divlist.html
{% extends 'pricecheck/base.html' %}
{% block dashboard %}active{% endblock %}
{% block dashboard_divlist %}active{% endblock %}

{% block Content %}
<div class="container-fluid">
    <div class="row">
        {% include 'pricecheck/partials/dashboard_sidebar.html' with dashboard_divlist="active" %}
        <div class="col-md-10">
            <div class="container-fluid">
                <br>
                <div class="card-header">
                    <div class="d-flex">
                        <h6 class="m-0-fonnr-weight-bold text-primary">時価乖離リスト</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover table-sm" style="table-layout;fixed"
                                data-toggle="table" data-search="true">
                                <thead>
                                    <tr>
                                        <th data-width="50px" data-halign="center" data-align="right">#</th>
                                        <th data-width="100px" data-halign="center" data-align="right">ファンドコード</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in d_div %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{i.fund_id|default_if_none:''}}</td>

                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

proj/templates/pricecheck/fund.html
{% extends 'pricecheck/base.html' %}
{% block fund %}active{% endblock %}

{% block Content %}
<div class="container-fluid">
    <div id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse min-vh-100">
        <div class="position-sticky pt-3">
            <form method="POST">
                {%csrf_token%}
                <div>
                    <label>{{form.fund_id.label}}:</label>
                    <br>
                    {{form.fund_id}}
                </div>
                <div>
                    <label>{{form.as_of_date.label}}:</label>
                    <br>
                    {{form.as_of_date}}
                </div>
                <hr>
                <button type="submit" class="btn btn-primary btn-sw w-100">load</button>
            </form>
        </div>
    </div>
    <main class="col-md-9 ms-sm-auto col-lg-10 pt-md-4">

    </main>
</div>
{% endblock %}

proj/templates/pricecheck/partials/dashboard_sidebar.html
<div class="col-md-2 bg-light min-vh-100">
    <br>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{% url 'pricecheck:dashboard_divlist' %}" class="nav-link {{dashboard_divlist}}">
                時価乖離リスト
            </a>
        </li>
    </ul>
</div>

proj/templates/pricecheck/partials/modal_国内株式.html
<div class="modal fade" id="exampleModalToggle" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalToggleLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h6>入力データ状況</h6>
                <table border="1" style="width:100%">
                    <tr>
                        <td>○</td>
                        <td>作業日</td>
                        <td>2023-04-11</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>残高日</td>
                        <td>2023-04-11</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>時価取得日</td>
                        <td>2023-04-11</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>決算日</td>
                        <td>2023-04-11</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>休日決算か</td>
                        <td>NO</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>ファンドタイプ</td>
                        <td>通常ファンド</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>中間／期末</td>
                        <td>中間</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>為替レート</td>
                        <td>取得済み</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>時価</td>
                        <td>取得済み</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A.ダウンロード</td>
                        <td>C:\Tmp\残高.xls</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A.ダウンロード(PY)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A2.ダウンロード(円建外債)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A2.ダウンロード(円建外債)(PY)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A3.ダウンロード(CP)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A3.ダウンロード(CP)(PY)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A4.外国WPM</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A5.国内取引経過</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A6.外国取引経過(円建外債)</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>A7.CP取引経過</td>
                        <td>元データファイル不明</td>
                    </tr>
                    <tr>
                        <td>○</td>
                        <td>B.有価証券明細</td>
                        <td>元データファイル不明</td>
                    </tr>

                </table>
            </div>
            <div class="modal-footer">
                <div class="container">
                    <div class="row gy-2">
                        <div class="col-6">
                            <button type="button" class="btn btn-primary w-100">銘柄別明細</button>
                        </div>
                        <div class="col-6">
                            <button type="button" class="btn btn-primary w-100">FSチェック用</button>
                        </div>
                        <div class="col-6">
                            <button type="button" class="btn btn-primary w-100">休日外国アキュム単価反映</button>
                        </div>
                        <div class="col-6">
                            <button type="button" class="btn btn-primary w-100">評価差額追加検証</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

proj/templates/pricecheck/partials/popover.html

<div id="popover_content">
    <!--ポップオーバー内表示用html-->
    <div id="popover_9997">
        <div class="popover-body">
            <table border="1">
                <tr>
                    <td>○</td>
                    <td>作業日</td>
                </tr>
                <tr>
                    <td>○</td>
                    <td>残高日</td>
                </tr>
                <tr>
                    <td>○</td>
                    <td>時価取得日</td>
                </tr>
                <tr>
                    <td>○</td>
                    <td>決算日</td>
                </tr>
                <tr>
                    <td>○</td>
                    <td>残高ファイル</td>
                </tr>
                <tr>
                    <td>○</td>
                    <td>ファンドタイプ</td>
                </tr>
            </table>
        </div>
    </div>
</div>